### PR TITLE
Make addStyle() & Chameleon types public

### PR DESCRIPTION
**Pull request by Ratakor**
- Make addStyle function public to allow for better meta programming. 
- Make Chameleon types public to enable better type safety.

### CODE REVIEW

**Comment by tr1ckydev** [comment]
Please provide a valid description for your PR.

**Comment by Ratakor** [comment]
@tr1ckydev done.

**Comment by tr1ckydev** [comment]
Just curious, what kind of metaprogramming are you doing with addStyle?

**Comment by Ratakor** [comment]
> Just curious, what kind of metaprogramming are you doing with addStyle?

https://github.com/Ratakor/clog/blob/c7112af746697452fc28431647dc9099927c8c36/src/clog.zig#L457

Since the interface for styles was not what I needed I made my own with an union(enum), the big switch is mainly because I prefer to stick to zig's naming style.

**Pull request merged**
